### ISSUE TITLE
Forms not shown when shown from the callback of another form

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/smartfs#10]
I have a form that calls a function in it callback, and that function can open another smartfs form. It seems like even though the form's code is run (using print statements), it does not get displayed to the user, and it also seems to break the existing form. It works properly if I put the second form-show in an after(0).

**Comment by bell07** [comment]
Should be fixed in https://github.com/bell07/minetest-smartfs/commit/aef4d9af20629f6ad908262e2a58ff8c807cfd23
Tested with nodemeta only, but should work with other locations too

**Comment by bell07** [comment]
Should be finally closed in 28b4bc8eed83b4fc8f75af051b1ac81504881c32
@raymoo are you still interested on solution? Can you test your code with the smartfs from my fork?

**Comment by raymoo** [comment]
I don't even remember what code I was using, but I think a small example would be easy to make anyway. Also why not open a PR to this repo?

**Comment by bell07** [comment]
> Also why not open a PR to this repo?
I did a lot of changes in my fork and take PR's one after the other. rubenwardy does quality check before merging them. So I wait at the time the "Container" PR is merged, before I create the next PR. But it seems rubenwardy does not have time anymore for smartfs :-(

**Comment by raymoo** [comment]
Well, it's under minetest-mods, so if rubenwardy is inactivate then theoretically someone who maintains minetest-mods could merge it.

**Comment by rubenwardy** [comment]
:gift: 

https://github.com/minetest-mods/smartfs/commit/3de2eacda534c53f8634bc8a94e24bcab3ea18fb #37

**Comment by bell07** [comment]
The paranoid state cleanup is merged that should prevent issues like this. 
Therefore closed. If a similar issue appears again, please create new issue
