### ISSUE TITLE
Code cleanup: move state:_show_()  to state.location:_show_()

### ISSUE THREAD

**Issue by bell07** [minetest-mods/smartfs#15]
state:_show_() should be a method of the new location object. That will be save the redundant "if location.type elseif location.type" in the _show_, just call the right code by state.location:_show_()

**Comment by rubenwardy** [comment]
:+1:

basically like fake classes for location, good enough

**Comment by bell07** [comment]
Done in my fork. I did not like to create a new "if native inventory" so the hacky "autodetection" of location is removed,  there is a proper differentiation now for unified_inventory, inventory_plus, inventory, nodemeta and view locations.

**Comment by bell07** [comment]
https://github.com/minetest-mods/smartfs/pull/40

**Comment by bell07** [comment]
PR merged
