### ISSUE TITLE
Allow private nodemeta?

### ISSUE THREAD

**Issue by sofar** [minetest-mods/smartfs#44]
https://github.com/minetest-mods/smartfs/blob/99e8809ffdce8a383e0f2400a450af389e37be4c/smartfs.lua#L242

Can you perhaps add an optional boolean parameter to make the nodemeta field here marked as private?

**Comment by bell07** [comment]
Good Idea, according the formspec security, thanks for suggestion!
It should not be optional, the formspec state should be server-site only.

**Comment by rubenwardy** [comment]
>  It should not be optional, the formspec state should be server-site only.

Agreed, there's no need for anything but `formspec` to be public

**Comment by bell07** [comment]
The issue was about smartfs_name only? I tested it with qa_block, works as expected without issues,
