### ISSUE TITLE
Add the ability to register in inventory mods without displaying the player inventory.

### ISSUE THREAD

**Issue by shacknetisp** [minetest-mods/smartfs#49]
In unified inventory this can be accomplished with `fsdata.draw_inventory = false` in the `get_formspec` return.
In sfinv, pass `false` after the actual formspec string to `sfinv.make_formspec`.

What is the best way to implement this?

**Comment by bell07** [comment]
I prefer an additional parameter "show_inv" is passed to the both calls

smartfs.add_to_inventory(form, icon, title, **show_inv**)
...
ldef.add_to_inventory(form, icon, title, **show_inv**)
